export default [
    {
        id: 1,
        name:"Déesse de la Téléportation",
        sprite_god:"../gods/Déesse_de_la_téléportation/Déesse_de_la_Téléportation_IA_-_Couleur.png",
        sprite_sign:"../gods/Déesse_de_la_téléportation/Signe_de_la_Téléportation.png",
        sprite_pawn:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Pion.png",
        sprite_knight:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Cavalier.png",
        sprite_bishop:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Fou.png",
        sprite_rook:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Tour.png",
        sprite_queen:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Reine.png",
        sprite_king:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Roi.png",
        explanation_power_passif:"Chaque pièces possèdent sa zone de téléportation. La téléportation est obligatoirement symétrique par rapport à la pièce. Une pièce jouée sur une case comprenant deux zones de téléportation ou plus, la téléportation ne s’effectue pas. Il ne peut y avoir qu’une téléportation au cours d’un mouvement. Les pièces adverses ne peuvent pas activer la téléportation.",
        explanation_power_pawn:"Zone de téléportation d’une case derrière.",
        explanation_power_knight:"Quand elle enjambe une pièce active la téléportation",
        explanation_power_bishop:"Zone de téléportation en croix.",
        explanation_power_rook:"Zone de téléportation en diagonale",
        explanation_power_queen:"Zone de téléportation tout autour d’elle.",
        explanation_power_king:"Zone de téléportation de trois cases en losange",
        gif_power_passif:"../gods/Déesse_de_la_téléportation/Plateau_d'échec_Spécial_gif_passif_1.gif",
        gif_power_pawn:"../gods/Déesse_de_la_téléportation/Plateau_d'échec_animation_téléportation_pion.gif",
        gif_power_knight:"../gods/Déesse_de_la_téléportation/Plateau_d'échec_animation_téléportation_cavalier.gif",
        gif_power_bishop:"../gods/Déesse_de_la_téléportation/Plateau_d'échec_animation_téléportation_fou_1.gif",
        gif_power_rook:"../gods/Déesse_de_la_téléportation/Plateau_d'échec_animation_téléportation_tour_1.gif",
        gif_power_queen:"../gods/Déesse_de_la_téléportation/Plateau_d'échec_animation_téléportation_reine_1.gif",
        gif_power_king:"../gods/Déesse_de_la_téléportation/Plateau_d'échec_animation_téléportation_roi_1.gif",
        
    },

    {
        id: 2,
        name:"Dieu de la Mort",
        sprite_god:"../gods/Dieu_de_la_mort/Dieu_de_la_Mort_IA_-_Couleur.png",
        sprite_sign:"../gods/Dieu_de_la_mort/Signe_de_la_Mort.png",
        sprite_pawn:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Pion.png",
        sprite_knight:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Cavalier.png",
        sprite_bishop:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Fou.png",
        sprite_rook:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Tour.png",
        sprite_queen:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Reine.png",
        sprite_king:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Roi.png",
        explanation_power_passif:"Lorsqu’une de vos pièces ce fait prendre par une pièces adverses, pose un compte à rebours sur une pièces adverse aléatoirement par rapport à l’échelle de force de GodChess. Le compte à rebours est de 5 tours. La faction pris ne peut poser un compte à rebours seulement sur une faction inférieur à lui (Exception lié à la faction des pions). L’effet de la mort ne s’active que si la pièce se fait prendre seulement.",
        explanation_power_pawn:"Tous les deux pions pris pose un compte à rebours tout d’abord sur les pions, puis pions et cavalier, puis pions,cavalier et fou et enfin pions, cavalier, fou et tour.",
        explanation_power_knight:"Pose un compte à rebours aléatoirement sur un pion adverse.",
        explanation_power_bishop:"Pose un compte à rebours aléatoirement sur un pion ou un cavalier adverse.",
        explanation_power_rook:"Pose un compte à rebours aléatoirement sur un pion, un cavalier ou un fou adverse.",
        explanation_power_queen:"Pose un compte à rebours aléatoirement sur un pion, un cavalier, un fou ou une tour adverse.",
        explanation_power_king:"Quand le roi se fait mettre en échec pose un compte un rebourssur n’importe quelles pièces.(3 utilisations)",
        gif_power_passif:"../gods/Dieu_de_la_mort/Plateau_d'échec_animation_Mort_passif_1.gif",
        gif_power_pawn:"../gods/Dieu_de_la_mort/Plateau_d'échec_animation_Mort_pion.gif",
        gif_power_knight:"../gods/Dieu_de_la_mort/Plateau_d'échec_animation_Mort_cavalier.gif",
        gif_power_bishop:"../gods/Dieu_de_la_mort/Plateau_d'échec_animation_Mort_fou.gif",
        gif_power_rook:"../gods/Dieu_de_la_mort/Plateau_d'échec_animation_Mort_tour.gif",
        gif_power_queen:"../gods/Dieu_de_la_mort/Plateau_d'échec_animation_Mort_reine.gif",
        gif_power_king:"../gods/Dieu_de_la_mort/Plateau_d'échec_animation_Mort_roi.gif",
    },

    {
        id: 3,
        name:"",
        sprite_god:"",
        sprite_sign:"",
        sprite_pawn:"",
        sprite_knight:"",
        sprite_bishop:"",
        sprite_rook:"",
        sprite_queen:"",
        sprite_king:"",
        explanation_power_passif:"",
        explanation_power_pawn:"",
        explanation_power_knight:"",
        explanation_power_bishop:"",
        explanation_power_rook:"",
        explanation_power_queen:"",
        explanation_power_king:"",
        gif_power_passif:"",
        gif_power_pawn:"",
        gif_power_knight:"",
        gif_power_bishop:"",
        gif_power_rook:"",
        gif_power_queen:"",
        gif_power_king:"",
    },
    
]