export default [
    {
        id: 1,
        name:"Déesse de la Téléportation",
        sprite_god:"../gods/Déesse_de_la_téléportation/Déesse_de_la_Téléportation_IA_-_Couleur.png",
        sprite_sign:"../gods/Déesse_de_la_téléportation/Signe_de_la_Téléportation.png",
        sprite_pawn:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Pion.png",
        sprite_knight:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Cavalier.png",
        sprite_bishop:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Fou.png",
        sprite_rook:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Tour.png",
        sprite_queen:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Reine.png",
        sprite_king:"../gods/Déesse_de_la_téléportation/Base_pièce_doubler_-_Roi.png",
        explanation_power_passif:"Chaque pièces possèdent sa zone de téléportation. La téléportation est obligatoirement symétrique par rapport à la pièce. Une pièce jouée sur une case comprenant deux zones de téléportation ou plus, la téléportation ne s’effectue pas. Il ne peut y avoir qu’une téléportation au cours d’un mouvement. Les pièces adverses ne peuvent pas activer la téléportation.",
        explanation_power_pawn:"Explication du Pion à mettre ici",
        explanation_power_knight:"",
        explanation_power_bishop:"",
        explanation_power_rook:"",
        explanation_power_queen:"",
        explanation_power_king:"",
        gif_power_passif:"../gods/Déesse_de_la_téléportation/Plateau_d'échec_Spécial_gif_passif_1.gif",
        gif_power_pawn:"Gif du Pion à mettre ici",
        gif_power_knight:"",
        gif_power_bishop:"",
        gif_power_rook:"",
        gif_power_queen:"",
        gif_power_king:"",
        
    },

    {
        id: 2,
        name:"Dieu de la Mort",
        sprite_god:"../gods/Dieu_de_la_mort/Dieu_de_la_Mort_IA_-_Couleur.png",
        sprite_sign:"../gods/Dieu_de_la_mort/Signe_de_la_Mort.png",
        sprite_pawn:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Pion.png",
        sprite_knight:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Cavalier.png",
        sprite_bishop:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Fou.png",
        sprite_rook:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Tour.png",
        sprite_queen:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Reine.png",
        sprite_king:"../gods/Dieu_de_la_mort/Base_pièce_doubler_-_Roi.png",
        explanation_power_passif:"Lorsqu’une de vos pièces ce fait prendre par une pièces adverses, pose un compte à rebours sur une pièces adverse aléatoirement par rapport à l’échelle de force de GodChess. Le compte à rebours est de 5 tours. La faction pris ne peut poser un compte à rebours seulement sur une faction inférieur à lui (Exception lié à la faction des pions). L’effet de la mort ne s’active que si la pièce se fait prendre seulement.",
        explanation_power_pawn:"Explication du Pion à mettre ici",
        explanation_power_knight:"",
        explanation_power_bishop:"",
        explanation_power_rook:"",
        explanation_power_queen:"",
        explanation_power_king:"",
        gif_power_passif:"../gods/Dieu_de_la_mort/Plateau_d'échec_animation_Mort_passif_1.gif",
        gif_power_pawn:"Gif du Pion à mettre ici",
        gif_power_knight:"",
        gif_power_bishop:"",
        gif_power_rook:"",
        gif_power_queen:"",
        gif_power_king:"",
    },

    {
        id: 3,
        name:"",
        sprite_god:"",
        sprite_sign:"",
        sprite_pawn:"",
        sprite_knight:"",
        sprite_bishop:"",
        sprite_rook:"",
        sprite_queen:"",
        sprite_king:"",
        explanation_power_passif:"",
        explanation_power_pawn:"",
        explanation_power_knight:"",
        explanation_power_bishop:"",
        explanation_power_rook:"",
        explanation_power_queen:"",
        explanation_power_king:"",
        gif_power_passif:"",
        gif_power_pawn:"",
        gif_power_knight:"",
        gif_power_bishop:"",
        gif_power_rook:"",
        gif_power_queen:"",
        gif_power_king:"",
    },
    
]